### ISSUE TITLE
Euclidean action as a function of temperature (and derivative)

### ISSUE THREAD

**Issue by runburg** [clwainwright/CosmoTransitions#28]
I may be missing something here, but I see that finding dS/dT is still listed as a todo. As far as I can tell, the action returned by transitionFinder.tunnelFromPhase is the action at the nucleation temperature. But it doesn't seem like the action as a function of temperature is stored.

Is there an easy way to do this? I saw that returning the derivative dS/dT was a todo so I imagine my request is not straightforward.

If there isn't, I would be interested in making these changes myself if that's useful. Thanks!

**Comment by clwainwright** [comment]
The easiest way to calculate it is to just run the `pathDeformation.fullTunneling()` function by feeding in your potential at a temperature that's slightly higher than the nucleation temperature and to take a finite difference in the action to calculate the derivative. See `transitionFinder_tunnelFromPhaseAtT()` to see how this is called. You _could_ also calculate the derivative by modifying the `tunnelFromPhase()` function to return the full `outdict` object (which contains tunneling information as a function of temperature), and then take finite differences from that, but that's a little more prone to error because you won't be in control of the finite step size in temperature.
